# Generated by Django 4.0.4 on 2022-05-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_image_alt_product_image_alt1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'KG')], default='Piece', max_length=100),
        ),
    ]
