# Generated by Django 4.0.4 on 2022-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='customertransaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
