# Generated by Django 4.0.4 on 2022-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_alter_customeraction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraction',
            name='age',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='age',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
