# Generated by Django 4.0.4 on 2022-06-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
    ]
