# Generated by Django 4.0.4 on 2022-05-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Balance',
            new_name='balance',
        ),
    ]
