# Generated by Django 4.0.4 on 2022-05-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_address_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
