# Generated by Django 4.0.4 on 2022-05-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Town',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='Zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.zone'),
        ),
    ]
