# Generated by Django 4.0.4 on 2022-05-23 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_city_zone_remove_address_phone_remove_address_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Zone',
        ),
        migrations.AddField(
            model_name='city',
            name='Zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.zone'),
        ),
    ]
