# Generated by Django 4.0.4 on 2022-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_region_zone_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kebelle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer'), ('delivery', 'Delivery'), ('admin', 'Admin')], default='Customer', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='woreda',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
