# Generated by Django 4.0.4 on 2022-05-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_orderproduct_paid_alter_bookorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
    ]
