# Generated by Django 4.0.4 on 2022-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_bookorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('ordered', 'Ordered'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
