# Generated by Django 4.0.4 on 2022-05-31 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_bookorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='updated',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
    ]
