# Generated by Django 4.0.4 on 2022-06-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_alter_orderproduct_options_remove_bookorder_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Order.bookorder'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
    ]
